version: '3.3'

services:
  # PostgreSQL Database (Local development)
  postgres:
    image: postgres:15-alpine
    container_name: healthcare_postgres
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: healthcare_user
      POSTGRES_PASSWORD: healthcare_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    networks:
      - healthcare_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthcare_user -d healthcare_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache (Local development)
  redis:
    image: redis:7-alpine
    container_name: healthcare_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - healthcare_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development Backend
  dev-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: healthcare_dev_backend
    environment:
      - DATABASE_URL=postgresql://healthcare_user:healthcare_password@postgres:5432/healthcare_db
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - LOG_LEVEL=debug
      - SECRET_KEY=dev-secret-key-not-for-production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key-here}
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - healthcare_network

  # Database Migration
  migration:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: healthcare_migration
    environment:
      - DATABASE_URL=postgresql://healthcare_user:healthcare_password@postgres:5432/healthcare_db
    volumes:
      - .:/app
    command: ["python", "migrate.py", "setup"]
    depends_on:
      - postgres
    networks:
      - healthcare_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  healthcare_network:
    driver: bridge
